### ISSUE TITLE
bug: v0.4.0 changes default ordering

### ISSUE THREAD

**Issue by twmb** [daixiang0/gci#71] opened 2022-07-08 17:51 UTC
https://github.com/daixiang0/gci/pull/70/files#r917027845

The already-good code changed from `standard, default, prefix(github.com/daixiang0/gci)` to `standard, prefix(github.com/daixiang0/gci), default` even though the sections configuration did not change: https://github.com/daixiang0/gci/blob/9349c88f1609b0e71ec5cac5576b1a413ac25869/pkg/gci/internal/testdata/common.cfg.yaml

**Comment by daixiang0** [comment] 2022-07-09 00:43
Yes, v0.4.0 introduces breaking changes.

**Comment by twmb** [comment] 2022-07-09 21:01
If I'm understanding it correctly, you're saying that it's no longer an option to organize custom imports after default?

My organization previously was:

* stdlib
* default
* org, non-repo
* org, repo

That's my only use case, and the one use case I see consistently across other repos and orgs, and have used for years.

**Comment by daixiang0** [comment] 2022-07-11 01:16
Now the imports like:
- standard
- custom
- default

The custom section is for your own org, the reason is based on how far the imports are from your repo. The "standard" is built-in, which should be first. The default section means all 3rd-party imports, should be last.

**Comment by Dreamacro** [comment] 2022-07-11 03:14
@daixiang0 I have installed the latest golangci-lint (ed4befe), but the auto-fix result is wrong.

```yaml
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(myorg)
```

the order of `sections` has no effect on the result. it makes the code become
* standard
* prefix(myorg)
* default

I confirmed that the prefix is working because when I commented it out, it was merged into default.

**Comment by daixiang0** [comment] 2022-07-11 06:01
The order is not related to your config :( 

Please check [doc](https://github.com/daixiang0/gci/blob/master/README.md)

**Comment by ImSingee** [comment] 2022-07-11 06:16
Is there something necessary reason for this breaking change?

**Comment by Dreamacro** [comment] 2022-07-11 06:20
It looks like `sections` is just sorting without an order relationship. So sad, I had to look for some other sort of linter 😢

**Comment by daixiang0** [comment] 2022-07-11 06:25
> Please check [doc](https://github.com/daixiang0/gci/blob/master/README.md)

Please check [doc](https://github.com/daixiang0/gci/blob/master/README.md), order is builtin.

**Comment by daixiang0** [comment] 2022-07-11 06:46
> It looks like `sections` is just sorting without an order relationship. So sad, I had to look for some other sort of linter 😢
> 
> UPDATE
> 
> When I install the pre-master golangci-lint `go install github.com/golangci/golangci-lint/cmd/golangci-lint@1d8a15a`
> 
> The order of `sections` will be sorted according to the expected results

There would be a misunderstanding that I never say the section order can be configured, I will update the document to make it clear.

**Comment by daixiang0** [comment] 2022-07-11 06:49
The default ordering will be revert as #72 @twmb @ImSingee 

Thanks for your input.

**Comment by daixiang0** [comment] 2022-07-11 08:12
@Dreamacro please try https://github.com/golangci/golangci-lint/commit/5e183652bafe34833a0975b378c8f1da8bb7769d

**Comment by daixiang0** [comment] 2022-07-12 00:37
@Dreamacro another bug, I will fix it soon.

**Comment by daixiang0** [comment] 2022-07-13 02:32
For order config support, tracked as https://github.com/daixiang0/gci/issues/74.

Close it by #72

**Closed by daixiang0** 2022-07-13 02:32 UTC

**Comment by twmb** [comment] 2022-07-14 03:07
Thank you @daixiang0,
I didn't realize the order wasn't controllable before because I had always ordered custom last.

**Comment by daixiang0** [comment] 2022-07-14 13:09
@Dreamacro not reproduce it, could you provide config and codes?

>  It seems that if the prefix contains uppercase letters, the packets are not aggregated properly.

**Comment by Dreamacro** [comment] 2022-07-14 13:24
@daixiang0 It can be reproduced on my repo: https://github.com/Dreamacro/clash

run `go install github.com/golangci/golangci-lint/cmd/golangci-lint@master` and add this on `.golangci.yaml`

```yaml
issues:
  fix: true
```

then run `make lint` and all not standard packages will group into one.

**Comment by Dreamacro** [comment] 2022-07-14 13:59
I tried the example.

* When the package has no uppercase characters

`gci write -s standard -s default -s "prefix(github.com/daixiang0/gci)" main.go`

```go
package main

import (
	"golang.org/x/tools"

	"fmt"

	"github.com/daixiang0/gci"
)
```

to

```go
package main

import (
	"fmt"

	"golang.org/x/tools"

	"github.com/daixiang0/gci"
)
```

* When the package has uppercase characters

`gci write -s standard -s default -s "prefix(github.com/Daixiang0/gci)" main.go`

```go
package main

import (
	"golang.org/x/tools"

	"fmt"

	"github.com/daixiang0/gci"
)
```

to

```go
package main

import (
	"fmt"

	"github.com/Daixiang0/gci"
	"golang.org/x/tools"
)
```
